name: Waka Detailed Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SECTION_NAME: waka

          SHOW_COMMIT: "True"
          COMMIT_BY_ME: "True"

          SHOW_TIMEZONE: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_SHORT_INFO: "True"

          SHOW_LANGUAGE: "True"
          SHOW_PROJECTS: "True"

          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"

          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_OS: "False"
          SHOW_EDITORS: "False"

          COMMIT_MESSAGE: "Updated WakaTime stats"