name: Waka Detailed Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          SECTION_NAME: waka

          SHOW_COMMIT: true
          COMMIT_BY_ME: true

          SHOW_TIMEZONE: true
          SHOW_UPDATED_DATE: true
          SHOW_SHORT_INFO: true

          SHOW_LANGUAGE: true
          SHOW_PROJECTS: true

          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true

          SHOW_LOC_CHART: true
          SHOW_DAYS_OF_WEEK: false
          SHOW_PROFILE_VIEWS: false
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_OS: false
          SHOW_EDITORS: false